# Generated by Django 2.2.16 on 2022-08-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220807_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name': 'Продуктовая корзина', 'verbose_name_plural': 'Продуктовые корзины'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
    ]
