# Generated by Django 2.2.16 on 2022-08-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220802_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Ingredients', verbose_name='Ингридиенты'),
        ),
    ]
